services:

  db:
    image: postgres
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - 8080:8080